### ISSUE TITLE
Segmentation sent_id=1mbs

### ISSUE THREAD

**Issue by robvanderg** [UniversalDependencies/UD_Ukrainian-IU#5]
The gold segmentation seems a bit off for sentence 1mbs:

я тупо закоханий з першого погляду (серйозно)...борюся з цим: наприклад написав
пісню(з посвятою моїй першій викладачці англійської та її дочці), яку ми з
групою тепер граємо!))може колись на концерті вона.... ех... солодкі, молочні,
кавові й гіркі, прекрасні і точні чорні очі твої......Катерино

The )) is a separate sentence, would it make sense to attach it to the previous sentence?

**Comment by msklvsk** [comment]
Indeed! Fixed in dev branch.
